#include "mc9s12xdp512.h"



#include <stdio.h>
#include "sci.h"

#include "rti.h"
#include "pll_asm.h"

#include "LEDscreen.h"
#include "ws2812b.h"

#define _putchar            (void)putchar
#define _printf            (void)printf


// ===================================================================
//8 *32 Pixel WS2812B WS2812 Digital Color Flexible Led Panel Display
// ===================================================================

  
// LED Internal Structure 
   
/*
typedef struct// es GRB

{
  unsigned char Green;
  unsigned char Red ;
  unsigned char Blue;
  
}LEDSTR; 

*/



int i,j;



static void system_init(void);
/////void init_display(void);


void WS2812B_Test(void);
void LEDtest(void);
void LEDtest2(void);
void Scitest(void);
void pointerAccessTest(void);
void pointerAccessTest2(void);







                       
void main(void) {                  
                                   



 pointerAccessTest2();
  
  
 
 system_init();
 
 _asm cli;
 
  for (;;)
  Scitest();
 
//  WS2812B_Test();

 
   
 
}




static void system_init(void) 
{


  #ifdef FLASH     

    pll_init();	  // solo para flash  (ver config.h)

  #endif				     
    
    Sci_Init();


    PORTA = 0x00;
    DDRA = 0xFF;
    
//    rti_init();
}



//*************** TEST AREA ***************//

//================================================


// This array is for testing WS2812B DIN on osciloscope

//unsigned char temp[]={0x00,0xFF,0x00, 0xFF,0x00,0x00, 0x00,0x00,0xFF};

//unsigned char temp[]={0x00,0x7F,0x00, 0x7F,0x00,0x00, 0x00,0x00,0x7F};

//unsigned char temp[]={0x00,0x30,0x00, 0x30,0x00,0x00, 0x00,0x00,0x30};

//unsigned char temp[]={0xff,0xfF,0xff, 0xfF,0xff,0xff, 0xff,0xff,0xfF};

unsigned char temp[]={0xff,0xfF,0xff, 0xfF,0xff,0xff, 0xff,0xff,0xfF,
0xff,0xfF,0xff, 0xfF,0xff,0xff, 0xff,0xff,0xfF,0xff,0xff,0xfF,0xff,0xff,0xfF };


void WS2812B_Test(void) {

  
 WS2812B_Init();
 WS2812B_Set_Data_pointer(temp);
 WS2812B_Set_Data_Length(sizeof(temp)/sizeof(temp[0]));
 WS2812B_Send_data();
 for (;;) ;   // stop for test
 



}

/* This test sends data generated by LEDscreen.c 
   to screen
 */

void LEDtest2(void) {
  
  unsigned char *pdata;  
    
    
    LEDscreen_setMSJ("HOLA MUNDO");
       
    pdata= (unsigned char*) LEDscreen_getScreenData();
    
    WS2812B_Init();
    
    WS2812B_Set_Data_pointer(pdata);
    
    WS2812B_Set_Data_Length(32*8*sizeof(LEDSTR));
        
    WS2812B_Send_data();


    
  ////  p2led3=(unsigned char (*)[TEST_COLS*sizeof(LEDSTR)])
    
       // ws2812B();
    
    LEDscreen_ShiftMSJ();
     
    
}     




/* This test evaluates how much time 
takes the LEDscreen_setMSJ to update
the screen */

void LEDtest(void) {
  
  LEDscreen_setMSJ("HOLA mundo");
    //programa principal                 
    for(;;) {
       
         PORTA |= 0x01;
        
       // LEDSTR *LEDscreen_getScreenData()
       // ws2812B();
        LEDscreen_ShiftMSJ();
         PORTA &= 0xFE;
        
       _asm nop;
       _asm nop;   
       _asm nop;
       _asm nop;
    }
   
  
}     


void Scitest(void) {
  
///////char c;
  
//   c=Sci1_Gechar();
//    Sci1_Putchar(c+1);



    //_putchar(0xA5);       // SCI 0
    //putchar(0xA5);         // SCI 0
    //putchar(0xA5);          // SCI 0
    //putchar(0xA5);           // SCI 0
    
    //_printf("  1234   ");         // SCI 0
   
   while (Sci1_GetQueueSatus()==EMPTY);           // SCI 1
   
   Sci1_Putchar(Sci1_GetQueueData()+2);
     
    
  
  
}


unsigned char *p2led=NULL;
LEDSTR *p2led2=NULL;


#define TEST_COLS 4
#define TEST_ROWS 8 

///

LEDSTR LedScreen [TEST_ROWS][TEST_COLS]={
{{0x01,0x02,0x03},{0x04,0x05,0x06},{0x07,0x08,0x09}},             // first 3 elem of first row (rest are zero)
{{0x10,0x20,0x30},{0x40,0x50,0x60},{0x70,0x80,0x90}},    // first 3 elem of second row (rest are zero)
{{0x11,0x12,0x13},{0x14,0x15,0x16},{0x17,0x18,0x19}}
};

unsigned char DestLedScreen [TEST_ROWS*TEST_COLS*sizeof(LEDSTR)];

/// 

void pointerAccessTest(void)
{
  
  p2led=(unsigned char *)LedScreen;  // This pointer will access array bytes
  p2led2 =(LEDSTR *) LedScreen;    // This pointer will access array elements
   
  p2led2->Blue=255;
  p2led2++;
  p2led2->Red=255;
  p2led2++;
  p2led2->Green=255;

  for(i=0;i<24;i++){
    
      *p2led=0x33;
      p2led++;
  }


}


unsigned char (*p2led3)[TEST_COLS*sizeof(LEDSTR)];  
unsigned char test_col=0;
unsigned char test_row=0;
    
unsigned char *pc;
unsigned char uc; 

void pointerAccessTest2(void)
{
  
 
  //
  ////////  return (LEDSTR *)LedScreen;
  
  
  p2led3=(unsigned char (*)[TEST_COLS*sizeof(LEDSTR)])LedScreen; 
  pc= DestLedScreen;

  while (1){
    
  
      
  // *** THIS TAKES MUCH TIME (uses IDIV)           
  /// uc=  *(*(p2led3 + row%TEST_ROWS)+col%TEST_COLS); 
 
 
   uc=  *(*(p2led3 + test_row)+test_col); 
        //uc=  p2led3[row][col];
        *pc++=uc;
  
        test_col++;
        
  
    if(test_col == TEST_COLS*sizeof(LEDSTR)) {
      
          test_row++;
          test_col=0;
    }
    
 
 
  
  
 // pc=*p2led3;     // Pointer to an array of 5 colums

 ///   p2led3++;
  }

}
